name: boozin_fitness
description: A professional fitness tracking app with Google Fit integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.7.3
  get_storage: ^2.1.1

  health: ^13.2.1 
  permission_handler: ^12.0.1

  # UI & Animations
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.7

  # Utilities
  intl: ^0.20.2
  logger: ^2.3.0
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#FFFFFF"
    color_dark: "#000000"